<?php

/**
 * @file
 * Primary module hooks for CDP User login form alter module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cdp_user_login_form_alter_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['name']['#access'] = FALSE;
  $form['mail'] = [
    '#type' => 'email',
    '#title' => t('E-mail'),
    '#description' => t('Enter your CDP Project user mail.'),
    '#required' => TRUE,
    '#weight' => -1,
  ];

  $form['#validate'] = array_merge(['_cdp_user_login_form_alter_validate_mail'], $form['#validate']);
}

function _cdp_user_login_form_alter_validate_mail(array &$form, FormStateInterface $form_state): void {
  $mail = $form_state->getValue('mail');

  if (filter_var($mail, FILTER_VALIDATE_EMAIL)) {
    $user = user_load_by_mail($mail);

    if ($user) {
      $form_state->setValue('name', $user->getAccountName());
    } else {
      $form_state->setErrorByName('mail', 'Wrong email address or user with such an email doesn\'t exist.');
    }
  } else {
    $form_state->setErrorByName('mail', 'Your provided email is not valid.');
  }
}
